// This file is auto-generated by @hey-api/openapi-ts

import { client } from './client.gen.js';
import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client/index.js';
import type { CancelSandboxOperationSandboxesSandboxIdCancelPostData, CancelSandboxOperationSandboxesSandboxIdCancelPostErrors, CancelSandboxOperationSandboxesSandboxIdCancelPostResponses, CapabilitiesSdkV1CapabilitiesGetData, CapabilitiesSdkV1CapabilitiesGetResponses, CreateSandboxData, CreateSandboxErrors, CreateSandboxResponses, DeleteSandboxData, DeleteSandboxErrors, DeleteSandboxResponses, DiagnosticsSdkV1DiagnosticsGetData, DiagnosticsSdkV1DiagnosticsGetResponses, EventsSdkV1EventsGetData, EventsSdkV1EventsGetResponses, ExecCommandData, ExecCommandErrors, ExecCommandResponses, GetSandboxData, GetSandboxDesktopData, GetSandboxDesktopErrors, GetSandboxDesktopResponses, GetSandboxErrors, GetSandboxResponses, ListSandboxesData, ListSandboxesResponses, ReadFileSandboxesSandboxIdFilesGetData, ReadFileSandboxesSandboxIdFilesGetErrors, ReadFileSandboxesSandboxIdFilesGetResponses, WriteFileSandboxesSandboxIdFilesPutData, WriteFileSandboxesSandboxIdFilesPutErrors, WriteFileSandboxesSandboxIdFilesPutResponses } from './types.gen.js';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Capabilities
 */
export const capabilitiesSdkV1CapabilitiesGet = <ThrowOnError extends boolean = false>(options?: Options<CapabilitiesSdkV1CapabilitiesGetData, ThrowOnError>): RequestResult<CapabilitiesSdkV1CapabilitiesGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CapabilitiesSdkV1CapabilitiesGetResponses, unknown, ThrowOnError>({ url: '/sdk/v1/capabilities', ...options });

/**
 * Events
 */
export const eventsSdkV1EventsGet = <ThrowOnError extends boolean = false>(options?: Options<EventsSdkV1EventsGetData, ThrowOnError>): RequestResult<EventsSdkV1EventsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<EventsSdkV1EventsGetResponses, unknown, ThrowOnError>({ url: '/sdk/v1/events', ...options });

/**
 * Diagnostics
 */
export const diagnosticsSdkV1DiagnosticsGet = <ThrowOnError extends boolean = false>(options?: Options<DiagnosticsSdkV1DiagnosticsGetData, ThrowOnError>): RequestResult<DiagnosticsSdkV1DiagnosticsGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<DiagnosticsSdkV1DiagnosticsGetResponses, unknown, ThrowOnError>({ url: '/sdk/v1/diagnostics', ...options });

/**
 * List Sandboxes
 */
export const listSandboxes = <ThrowOnError extends boolean = false>(options?: Options<ListSandboxesData, ThrowOnError>): RequestResult<ListSandboxesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSandboxesResponses, unknown, ThrowOnError>({ url: '/sandboxes', ...options });

/**
 * Create Sandbox
 */
export const createSandbox = <ThrowOnError extends boolean = false>(options: Options<CreateSandboxData, ThrowOnError>): RequestResult<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError> => (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
    url: '/sandboxes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Sandbox
 */
export const deleteSandbox = <ThrowOnError extends boolean = false>(options: Options<DeleteSandboxData, ThrowOnError>): RequestResult<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError> => (options.client ?? client).delete<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}', ...options });

/**
 * Get Sandbox
 */
export const getSandbox = <ThrowOnError extends boolean = false>(options: Options<GetSandboxData, ThrowOnError>): RequestResult<GetSandboxResponses, GetSandboxErrors, ThrowOnError> => (options.client ?? client).get<GetSandboxResponses, GetSandboxErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}', ...options });

/**
 * Get Sandbox Desktop
 */
export const getSandboxDesktop = <ThrowOnError extends boolean = false>(options: Options<GetSandboxDesktopData, ThrowOnError>): RequestResult<GetSandboxDesktopResponses, GetSandboxDesktopErrors, ThrowOnError> => (options.client ?? client).get<GetSandboxDesktopResponses, GetSandboxDesktopErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}/desktop', ...options });

/**
 * Cancel Sandbox Operation
 *
 * Stop an in-flight operation by deleting its session VM.
 */
export const cancelSandboxOperationSandboxesSandboxIdCancelPost = <ThrowOnError extends boolean = false>(options: Options<CancelSandboxOperationSandboxesSandboxIdCancelPostData, ThrowOnError>): RequestResult<CancelSandboxOperationSandboxesSandboxIdCancelPostResponses, CancelSandboxOperationSandboxesSandboxIdCancelPostErrors, ThrowOnError> => (options.client ?? client).post<CancelSandboxOperationSandboxesSandboxIdCancelPostResponses, CancelSandboxOperationSandboxesSandboxIdCancelPostErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}/cancel', ...options });

/**
 * Exec Command
 */
export const execCommand = <ThrowOnError extends boolean = false>(options: Options<ExecCommandData, ThrowOnError>): RequestResult<ExecCommandResponses, ExecCommandErrors, ThrowOnError> => (options.client ?? client).post<ExecCommandResponses, ExecCommandErrors, ThrowOnError>({
    url: '/sandboxes/{sandbox_id}/exec',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Read File
 */
export const readFileSandboxesSandboxIdFilesGet = <ThrowOnError extends boolean = false>(options: Options<ReadFileSandboxesSandboxIdFilesGetData, ThrowOnError>): RequestResult<ReadFileSandboxesSandboxIdFilesGetResponses, ReadFileSandboxesSandboxIdFilesGetErrors, ThrowOnError> => (options.client ?? client).get<ReadFileSandboxesSandboxIdFilesGetResponses, ReadFileSandboxesSandboxIdFilesGetErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}/files', ...options });

/**
 * Write File
 */
export const writeFileSandboxesSandboxIdFilesPut = <ThrowOnError extends boolean = false>(options: Options<WriteFileSandboxesSandboxIdFilesPutData, ThrowOnError>): RequestResult<WriteFileSandboxesSandboxIdFilesPutResponses, WriteFileSandboxesSandboxIdFilesPutErrors, ThrowOnError> => (options.client ?? client).put<WriteFileSandboxesSandboxIdFilesPutResponses, WriteFileSandboxesSandboxIdFilesPutErrors, ThrowOnError>({ url: '/sandboxes/{sandbox_id}/files', ...options });
