// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CapabilitiesResponse
 *
 * Runtime protocol and feature discovery.
 */
export type CapabilitiesResponse = {
    /**
     * Protocol Version
     */
    protocol_version?: 1;
    /**
     * Capabilities
     */
    capabilities?: Array<string>;
};

/**
 * CreateSandboxRequest
 *
 * Create and boot an SDK-session sandbox.
 */
export type CreateSandboxRequest = {
    /**
     * Image
     *
     * Image reference to boot. Omit to use the published image for the OS.
     */
    image?: string | null;
    /**
     * Os
     *
     * Guest OS. Ubuntu is the SDK default; Alpine is optional.
     */
    os?: 'alpine' | 'ubuntu' | null;
    /**
     * Memory
     *
     * Memory in MiB.
     */
    memory?: number | null;
    /**
     * Disk Size
     *
     * Root disk size in MiB.
     */
    disk_size?: number | null;
    /**
     * Backend
     *
     * Optional runtime backend override.
     */
    backend?: 'firecracker' | 'qemu' | 'libkrun' | 'vz' | null;
    /**
     * Network
     *
     * Outbound network policy.
     */
    network?: ({
        mode: 'open';
    } & OpenNetworkPolicy) | ({
        mode: 'off';
    } & OffNetworkPolicy) | ({
        mode: 'restricted';
    } & RestrictedNetworkPolicy);
};

/**
 * DesktopResponse
 *
 * A sanitized loopback display endpoint for a running sandbox.
 */
export type DesktopResponse = {
    /**
     * Protocol
     */
    protocol?: 'vnc';
    /**
     * Host
     */
    host: '127.0.0.1' | 'localhost' | '::1';
    /**
     * Port
     */
    port: number;
    /**
     * Viewer Url
     */
    viewer_url: string;
};

/**
 * DiagnosticsResponse
 *
 * Safe local runtime facts suitable for a bug report.
 */
export type DiagnosticsResponse = {
    /**
     * Protocol Version
     */
    protocol_version?: 1;
    /**
     * Runtime Version
     */
    runtime_version: string;
    /**
     * Python Version
     */
    python_version: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Supported
     */
    supported: boolean;
    /**
     * Problems
     */
    problems?: Array<string>;
};

/**
 * ErrorResponse
 *
 * The body returned for a handled API error.
 */
export type ErrorResponse = {
    /**
     * Detail
     *
     * Short explanation with a recovery action.
     */
    detail: string;
};

/**
 * ExecRequest
 *
 * Run one command inside a sandbox.
 */
export type ExecRequest = {
    /**
     * Command
     */
    command: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Shell
     */
    shell?: 'login' | 'raw';
    /**
     * Cwd
     *
     * Absolute working directory in the guest.
     */
    cwd?: string | null;
    /**
     * Env
     */
    env?: {
        [key: string]: string;
    };
};

/**
 * ExecResponse
 *
 * Captured command result. Non-zero exits are successful HTTP responses.
 */
export type ExecResponse = {
    /**
     * Exit Code
     */
    exit_code: number;
    /**
     * Stdout
     */
    stdout: string;
    /**
     * Stderr
     */
    stderr: string;
    /**
     * Duration Ms
     */
    duration_ms?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OffNetworkPolicy
 *
 * Block outbound network access.
 */
export type OffNetworkPolicy = {
    /**
     * Mode
     */
    mode: 'off';
};

/**
 * OpenNetworkPolicy
 *
 * Allow all outbound network access.
 */
export type OpenNetworkPolicy = {
    /**
     * Mode
     */
    mode: 'open';
};

/**
 * RestrictedNetworkPolicy
 *
 * Allow outbound access only to the supplied IPv4 ranges.
 */
export type RestrictedNetworkPolicy = {
    /**
     * Mode
     */
    mode: 'restricted';
    /**
     * Allowed Cidrs
     */
    allowed_cidrs: Array<string>;
};

/**
 * SandboxResponse
 *
 * Public state for one session-owned sandbox.
 */
export type SandboxResponse = {
    /**
     * Id
     */
    id: string;
    status: VmState;
};

/**
 * VMState
 *
 * VM lifecycle states.
 */
export type VmState = 'created' | 'running' | 'paused' | 'stopped' | 'error';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type CapabilitiesSdkV1CapabilitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk/v1/capabilities';
};

export type CapabilitiesSdkV1CapabilitiesGetResponses = {
    /**
     * Successful Response
     */
    200: CapabilitiesResponse;
};

export type CapabilitiesSdkV1CapabilitiesGetResponse = CapabilitiesSdkV1CapabilitiesGetResponses[keyof CapabilitiesSdkV1CapabilitiesGetResponses];

export type EventsSdkV1EventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk/v1/events';
};

export type EventsSdkV1EventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DiagnosticsSdkV1DiagnosticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk/v1/diagnostics';
};

export type DiagnosticsSdkV1DiagnosticsGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticsResponse;
};

export type DiagnosticsSdkV1DiagnosticsGetResponse = DiagnosticsSdkV1DiagnosticsGetResponses[keyof DiagnosticsSdkV1DiagnosticsGetResponses];

export type ListSandboxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type ListSandboxesResponses = {
    /**
     * Response Listsandboxes
     *
     * Successful Response
     */
    200: Array<SandboxResponse>;
};

export type ListSandboxesResponse = ListSandboxesResponses[keyof ListSandboxesResponses];

export type CreateSandboxData = {
    body: CreateSandboxRequest;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * Successful Response
     */
    201: SandboxResponse;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type DeleteSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type DeleteSandboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSandboxError = DeleteSandboxErrors[keyof DeleteSandboxErrors];

export type DeleteSandboxResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSandboxResponse = DeleteSandboxResponses[keyof DeleteSandboxResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type GetSandboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * Successful Response
     */
    200: SandboxResponse;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type GetSandboxDesktopData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/desktop';
};

export type GetSandboxDesktopErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSandboxDesktopError = GetSandboxDesktopErrors[keyof GetSandboxDesktopErrors];

export type GetSandboxDesktopResponses = {
    /**
     * Successful Response
     */
    200: DesktopResponse;
};

export type GetSandboxDesktopResponse = GetSandboxDesktopResponses[keyof GetSandboxDesktopResponses];

export type CancelSandboxOperationSandboxesSandboxIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/cancel';
};

export type CancelSandboxOperationSandboxesSandboxIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelSandboxOperationSandboxesSandboxIdCancelPostError = CancelSandboxOperationSandboxesSandboxIdCancelPostErrors[keyof CancelSandboxOperationSandboxesSandboxIdCancelPostErrors];

export type CancelSandboxOperationSandboxesSandboxIdCancelPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CancelSandboxOperationSandboxesSandboxIdCancelPostResponse = CancelSandboxOperationSandboxesSandboxIdCancelPostResponses[keyof CancelSandboxOperationSandboxesSandboxIdCancelPostResponses];

export type ExecCommandData = {
    body: ExecRequest;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/exec';
};

export type ExecCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecCommandError = ExecCommandErrors[keyof ExecCommandErrors];

export type ExecCommandResponses = {
    /**
     * Successful Response
     */
    200: ExecResponse;
};

export type ExecCommandResponse = ExecCommandResponses[keyof ExecCommandResponses];

export type ReadFileSandboxesSandboxIdFilesGetData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/sandboxes/{sandbox_id}/files';
};

export type ReadFileSandboxesSandboxIdFilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileSandboxesSandboxIdFilesGetError = ReadFileSandboxesSandboxIdFilesGetErrors[keyof ReadFileSandboxesSandboxIdFilesGetErrors];

export type ReadFileSandboxesSandboxIdFilesGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type WriteFileSandboxesSandboxIdFilesPutData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/sandboxes/{sandbox_id}/files';
};

export type WriteFileSandboxesSandboxIdFilesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteFileSandboxesSandboxIdFilesPutError = WriteFileSandboxesSandboxIdFilesPutErrors[keyof WriteFileSandboxesSandboxIdFilesPutErrors];

export type WriteFileSandboxesSandboxIdFilesPutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type WriteFileSandboxesSandboxIdFilesPutResponse = WriteFileSandboxesSandboxIdFilesPutResponses[keyof WriteFileSandboxesSandboxIdFilesPutResponses];
