// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * BrowserSessionResponse
 *
 * Ready browser session endpoints returned only to the owning SDK client.
 */
export type BrowserSessionResponse = {
    /**
     * Session Id
     */
    session_id: string;
    /**
     * Sandbox Id
     */
    sandbox_id: string;
    status: BrowserSessionState;
    /**
     * Cdp Url
     */
    cdp_url: string;
    /**
     * Viewer Url
     */
    viewer_url?: string | null;
    /**
     * Display Url
     */
    display_url?: string | null;
    /**
     * Profile Id
     */
    profile_id?: string | null;
};

/**
 * BrowserSessionState
 *
 * Browser session lifecycle states.
 */
export type BrowserSessionState = 'created' | 'starting' | 'ready' | 'stopping' | 'error' | 'deleted';

/**
 * BrowserViewportRequest
 *
 * Requested browser viewport in CSS pixels.
 */
export type BrowserViewportRequest = {
    /**
     * Width
     */
    width?: number;
    /**
     * Height
     */
    height?: number;
};

/**
 * CapabilitiesResponse
 *
 * Runtime protocol and feature discovery.
 */
export type CapabilitiesResponse = {
    /**
     * Protocol Version
     */
    protocol_version?: 1;
    /**
     * Capabilities
     */
    capabilities?: Array<string>;
};

/**
 * ComputerBrowserResponse
 *
 * State and automation address for Chromium inside a computer.
 */
export type ComputerBrowserResponse = {
    /**
     * Status
     */
    status: 'ready' | 'closed' | 'error';
    /**
     * Cdp Url
     */
    cdp_url: string | null;
};

/**
 * ComputerDisplayResponse
 *
 * Addresses for watching or controlling a computer display.
 */
export type ComputerDisplayResponse = {
    /**
     * Viewer Url
     */
    viewer_url: string;
    /**
     * Vnc Url
     */
    vnc_url: string;
};

/**
 * ComputerResourcesRequest
 *
 * CPU, memory, and disk requested for a Linux computer.
 */
export type ComputerResourcesRequest = {
    /**
     * Memory Mib
     */
    memory_mib?: number;
    /**
     * Disk Mib
     */
    disk_mib?: number;
    /**
     * Vcpus
     */
    vcpus?: 2;
};

/**
 * ComputerResponse
 *
 * A ready Linux computer and its grouped application endpoints.
 */
export type ComputerResponse = {
    /**
     * Computer Id
     */
    computer_id: string;
    /**
     * Sandbox Id
     */
    sandbox_id: string;
    /**
     * Template
     */
    template: 'linux-desktop';
    /**
     * Status
     */
    status: 'ready';
    /**
     * Capabilities
     */
    capabilities: Array<'display.viewer' | 'display.vnc' | 'browser.cdp' | 'sandbox.exec' | 'sandbox.files'>;
    display: ComputerDisplayResponse;
    browser: ComputerBrowserResponse;
};

/**
 * CreateBrowserSessionRequest
 *
 * Create and boot a browser session owned by one SDK client.
 */
export type CreateBrowserSessionRequest = {
    /**
     * Session Id
     */
    session_id?: string | null;
    /**
     * Mode
     */
    mode?: 'headless' | 'live';
    /**
     * Backend
     */
    backend?: 'firecracker' | 'qemu' | 'libkrun' | 'auto';
    /**
     * Profile Mode
     */
    profile_mode?: 'ephemeral' | 'persistent';
    /**
     * Profile Id
     */
    profile_id?: string | null;
    /**
     * Timeout Minutes
     */
    timeout_minutes?: number;
    viewport?: BrowserViewportRequest;
    /**
     * Record Video
     */
    record_video?: boolean;
    /**
     * Allow Downloads
     */
    allow_downloads?: boolean;
    /**
     * Memory
     */
    memory?: number;
    /**
     * Disk Size
     */
    disk_size?: number;
    /**
     * Network
     */
    network?: ({
        mode: 'open';
    } & OpenNetworkPolicy) | ({
        mode: 'off';
    } & OffNetworkPolicy) | ({
        mode: 'restricted';
    } & RestrictedNetworkPolicy);
};

/**
 * CreateComputerRequest
 *
 * Create a ready Linux computer owned by one SDK client.
 */
export type CreateComputerRequest = {
    /**
     * Computer Id
     */
    computer_id?: string | null;
    /**
     * Template
     */
    template?: 'linux-desktop';
    /**
     * Backend
     */
    backend?: 'firecracker' | 'qemu' | 'auto';
    display?: BrowserViewportRequest;
    resources?: ComputerResourcesRequest;
    /**
     * Network
     */
    network?: ({
        mode: 'open';
    } & OpenNetworkPolicy) | ({
        mode: 'off';
    } & OffNetworkPolicy) | ({
        mode: 'restricted';
    } & RestrictedNetworkPolicy);
    /**
     * Workspace
     */
    workspace?: Array<WorkspaceMount>;
};

/**
 * CreateSandboxRequest
 *
 * Create and boot an SDK-session sandbox.
 */
export type CreateSandboxRequest = {
    /**
     * Image
     *
     * Image reference to boot. Omit to use the published image for the OS.
     */
    image?: string | null;
    /**
     * Os
     *
     * Guest OS. Ubuntu is the SDK default; Alpine is optional.
     */
    os?: 'alpine' | 'ubuntu' | null;
    /**
     * Memory
     *
     * Memory in MiB.
     */
    memory?: number | null;
    /**
     * Disk Size
     *
     * Root disk size in MiB.
     */
    disk_size?: number | null;
    /**
     * Backend
     *
     * Optional runtime backend override.
     */
    backend?: 'firecracker' | 'qemu' | 'libkrun' | 'vz' | null;
    /**
     * Network
     *
     * Outbound network policy.
     */
    network?: ({
        mode: 'open';
    } & OpenNetworkPolicy) | ({
        mode: 'off';
    } & OffNetworkPolicy) | ({
        mode: 'restricted';
    } & RestrictedNetworkPolicy);
};

/**
 * DesktopResponse
 *
 * A sanitized loopback display endpoint for a running sandbox.
 */
export type DesktopResponse = {
    /**
     * Protocol
     */
    protocol?: 'vnc';
    /**
     * Host
     */
    host: '127.0.0.1' | 'localhost' | '::1';
    /**
     * Port
     */
    port: number;
    /**
     * Viewer Url
     */
    viewer_url: string;
};

/**
 * DiagnosticsResponse
 *
 * Safe local runtime facts suitable for a bug report.
 */
export type DiagnosticsResponse = {
    /**
     * Protocol Version
     */
    protocol_version?: 1;
    /**
     * Runtime Version
     */
    runtime_version: string;
    /**
     * Python Version
     */
    python_version: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Supported
     */
    supported: boolean;
    /**
     * Problems
     */
    problems?: Array<string>;
};

/**
 * ErrorResponse
 *
 * The body returned for a handled API error.
 */
export type ErrorResponse = {
    /**
     * Detail
     *
     * Short explanation with a recovery action.
     */
    detail: string;
};

/**
 * ExecRequest
 *
 * Run one command inside a sandbox.
 */
export type ExecRequest = {
    /**
     * Command
     */
    command: string;
    /**
     * Timeout
     */
    timeout?: number;
    /**
     * Shell
     */
    shell?: 'login' | 'raw';
    /**
     * Cwd
     *
     * Absolute working directory in the guest.
     */
    cwd?: string | null;
    /**
     * Env
     */
    env?: {
        [key: string]: string;
    };
};

/**
 * ExecResponse
 *
 * Captured command result. Non-zero exits are successful HTTP responses.
 */
export type ExecResponse = {
    /**
     * Exit Code
     */
    exit_code: number;
    /**
     * Stdout
     */
    stdout: string;
    /**
     * Stderr
     */
    stderr: string;
    /**
     * Duration Ms
     */
    duration_ms?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OffNetworkPolicy
 *
 * Block outbound network access.
 */
export type OffNetworkPolicy = {
    /**
     * Mode
     */
    mode: 'off';
};

/**
 * OpenNetworkPolicy
 *
 * Allow all outbound network access.
 */
export type OpenNetworkPolicy = {
    /**
     * Mode
     */
    mode: 'open';
};

/**
 * RestrictedNetworkPolicy
 *
 * Allow outbound access only to the supplied IPv4 ranges.
 */
export type RestrictedNetworkPolicy = {
    /**
     * Mode
     */
    mode: 'restricted';
    /**
     * Allowed Cidrs
     */
    allowed_cidrs: Array<string>;
};

/**
 * SandboxResponse
 *
 * Public state for one session-owned sandbox.
 */
export type SandboxResponse = {
    /**
     * Id
     */
    id: string;
    status: VmState;
};

/**
 * VMState
 *
 * VM lifecycle states.
 */
export type VmState = 'created' | 'running' | 'paused' | 'stopped' | 'error';

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkspaceMount
 *
 * Host directory to mount inside the guest via virtio-9p.
 *
 * By default the host directory is exposed read-only through QEMU's
 * virtio-9p passthrough, with an overlayfs layer on top so the guest
 * can read and write freely — changes stay inside the VM and never
 * touch the host.
 *
 * When ``writable`` is True the host directory is exposed read-write
 * and mounted directly at ``guest_path`` (no overlay), so writes from
 * the guest are visible on the host.
 *
 * Attributes:
 * host_path: Absolute path to a directory on the host.
 * guest_path: Mount point inside the guest (default ``/workspace``).
 * mount_tag: 9p mount tag passed to QEMU.  Auto-generated when omitted.
 * writable: When True, guest writes propagate to the host directory.
 * Default False (read-only host, writable overlay in guest).
 */
export type WorkspaceMount = {
    /**
     * Host Path
     */
    host_path: string;
    /**
     * Guest Path
     */
    guest_path?: string;
    /**
     * Mount Tag
     */
    mount_tag?: string | null;
    /**
     * Writable
     */
    writable?: boolean;
};

export type CapabilitiesSdkV1CapabilitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk/v1/capabilities';
};

export type CapabilitiesSdkV1CapabilitiesGetResponses = {
    /**
     * Successful Response
     */
    200: CapabilitiesResponse;
};

export type CapabilitiesSdkV1CapabilitiesGetResponse = CapabilitiesSdkV1CapabilitiesGetResponses[keyof CapabilitiesSdkV1CapabilitiesGetResponses];

export type EventsSdkV1EventsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk/v1/events';
};

export type EventsSdkV1EventsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DiagnosticsSdkV1DiagnosticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sdk/v1/diagnostics';
};

export type DiagnosticsSdkV1DiagnosticsGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticsResponse;
};

export type DiagnosticsSdkV1DiagnosticsGetResponse = DiagnosticsSdkV1DiagnosticsGetResponses[keyof DiagnosticsSdkV1DiagnosticsGetResponses];

export type CreateComputerData = {
    body: CreateComputerRequest;
    path?: never;
    query?: never;
    url: '/computers';
};

export type CreateComputerErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateComputerError = CreateComputerErrors[keyof CreateComputerErrors];

export type CreateComputerResponses = {
    /**
     * Successful Response
     */
    201: ComputerResponse;
};

export type CreateComputerResponse = CreateComputerResponses[keyof CreateComputerResponses];

export type DeleteComputerData = {
    body?: never;
    path: {
        /**
         * Computer Id
         */
        computer_id: string;
    };
    query?: never;
    url: '/computers/{computer_id}';
};

export type DeleteComputerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteComputerError = DeleteComputerErrors[keyof DeleteComputerErrors];

export type DeleteComputerResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteComputerResponse = DeleteComputerResponses[keyof DeleteComputerResponses];

export type CancelComputerOperationComputersComputerIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Computer Id
         */
        computer_id: string;
    };
    query?: never;
    url: '/computers/{computer_id}/cancel';
};

export type CancelComputerOperationComputersComputerIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelComputerOperationComputersComputerIdCancelPostError = CancelComputerOperationComputersComputerIdCancelPostErrors[keyof CancelComputerOperationComputersComputerIdCancelPostErrors];

export type CancelComputerOperationComputersComputerIdCancelPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CancelComputerOperationComputersComputerIdCancelPostResponse = CancelComputerOperationComputersComputerIdCancelPostResponses[keyof CancelComputerOperationComputersComputerIdCancelPostResponses];

export type ExecComputerCommandData = {
    body: ExecRequest;
    path: {
        /**
         * Computer Id
         */
        computer_id: string;
    };
    query?: never;
    url: '/computers/{computer_id}/exec';
};

export type ExecComputerCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecComputerCommandError = ExecComputerCommandErrors[keyof ExecComputerCommandErrors];

export type ExecComputerCommandResponses = {
    /**
     * Successful Response
     */
    200: ExecResponse;
};

export type ExecComputerCommandResponse = ExecComputerCommandResponses[keyof ExecComputerCommandResponses];

export type ReadComputerFileData = {
    body?: never;
    path: {
        /**
         * Computer Id
         */
        computer_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/computers/{computer_id}/files';
};

export type ReadComputerFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadComputerFileError = ReadComputerFileErrors[keyof ReadComputerFileErrors];

export type ReadComputerFileResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type WriteComputerFileData = {
    body?: never;
    path: {
        /**
         * Computer Id
         */
        computer_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/computers/{computer_id}/files';
};

export type WriteComputerFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteComputerFileError = WriteComputerFileErrors[keyof WriteComputerFileErrors];

export type WriteComputerFileResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type WriteComputerFileResponse = WriteComputerFileResponses[keyof WriteComputerFileResponses];

export type LaunchComputerBrowserData = {
    body?: never;
    path: {
        /**
         * Computer Id
         */
        computer_id: string;
    };
    query?: never;
    url: '/computers/{computer_id}/browser/launch';
};

export type LaunchComputerBrowserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LaunchComputerBrowserError = LaunchComputerBrowserErrors[keyof LaunchComputerBrowserErrors];

export type LaunchComputerBrowserResponses = {
    /**
     * Successful Response
     */
    200: ComputerBrowserResponse;
};

export type LaunchComputerBrowserResponse = LaunchComputerBrowserResponses[keyof LaunchComputerBrowserResponses];

export type CreateBrowserSessionData = {
    body: CreateBrowserSessionRequest;
    path?: never;
    query?: never;
    url: '/browser-sessions';
};

export type CreateBrowserSessionErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateBrowserSessionError = CreateBrowserSessionErrors[keyof CreateBrowserSessionErrors];

export type CreateBrowserSessionResponses = {
    /**
     * Successful Response
     */
    201: BrowserSessionResponse;
};

export type CreateBrowserSessionResponse = CreateBrowserSessionResponses[keyof CreateBrowserSessionResponses];

export type DeleteBrowserSessionData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/browser-sessions/{session_id}';
};

export type DeleteBrowserSessionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteBrowserSessionError = DeleteBrowserSessionErrors[keyof DeleteBrowserSessionErrors];

export type DeleteBrowserSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteBrowserSessionResponse = DeleteBrowserSessionResponses[keyof DeleteBrowserSessionResponses];

export type ExecBrowserCommandData = {
    body: ExecRequest;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query?: never;
    url: '/browser-sessions/{session_id}/exec';
};

export type ExecBrowserCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecBrowserCommandError = ExecBrowserCommandErrors[keyof ExecBrowserCommandErrors];

export type ExecBrowserCommandResponses = {
    /**
     * Successful Response
     */
    200: ExecResponse;
};

export type ExecBrowserCommandResponse = ExecBrowserCommandResponses[keyof ExecBrowserCommandResponses];

export type ReadBrowserFileData = {
    body?: never;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/browser-sessions/{session_id}/files';
};

export type ReadBrowserFileErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadBrowserFileError = ReadBrowserFileErrors[keyof ReadBrowserFileErrors];

export type ReadBrowserFileResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type ReadBrowserFileResponse = ReadBrowserFileResponses[keyof ReadBrowserFileResponses];

export type WriteBrowserFileData = {
    body: Blob | File;
    path: {
        /**
         * Session Id
         */
        session_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/browser-sessions/{session_id}/files';
};

export type WriteBrowserFileErrors = {
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteBrowserFileError = WriteBrowserFileErrors[keyof WriteBrowserFileErrors];

export type WriteBrowserFileResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type WriteBrowserFileResponse = WriteBrowserFileResponses[keyof WriteBrowserFileResponses];

export type ListSandboxesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type ListSandboxesResponses = {
    /**
     * Response Listsandboxes
     *
     * Successful Response
     */
    200: Array<SandboxResponse>;
};

export type ListSandboxesResponse = ListSandboxesResponses[keyof ListSandboxesResponses];

export type CreateSandboxData = {
    body: CreateSandboxRequest;
    path?: never;
    query?: never;
    url: '/sandboxes';
};

export type CreateSandboxErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSandboxError = CreateSandboxErrors[keyof CreateSandboxErrors];

export type CreateSandboxResponses = {
    /**
     * Successful Response
     */
    201: SandboxResponse;
};

export type CreateSandboxResponse = CreateSandboxResponses[keyof CreateSandboxResponses];

export type DeleteSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type DeleteSandboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSandboxError = DeleteSandboxErrors[keyof DeleteSandboxErrors];

export type DeleteSandboxResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteSandboxResponse = DeleteSandboxResponses[keyof DeleteSandboxResponses];

export type GetSandboxData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}';
};

export type GetSandboxErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSandboxError = GetSandboxErrors[keyof GetSandboxErrors];

export type GetSandboxResponses = {
    /**
     * Successful Response
     */
    200: SandboxResponse;
};

export type GetSandboxResponse = GetSandboxResponses[keyof GetSandboxResponses];

export type GetSandboxDesktopData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/desktop';
};

export type GetSandboxDesktopErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSandboxDesktopError = GetSandboxDesktopErrors[keyof GetSandboxDesktopErrors];

export type GetSandboxDesktopResponses = {
    /**
     * Successful Response
     */
    200: DesktopResponse;
};

export type GetSandboxDesktopResponse = GetSandboxDesktopResponses[keyof GetSandboxDesktopResponses];

export type CancelSandboxOperationSandboxesSandboxIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/cancel';
};

export type CancelSandboxOperationSandboxesSandboxIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelSandboxOperationSandboxesSandboxIdCancelPostError = CancelSandboxOperationSandboxesSandboxIdCancelPostErrors[keyof CancelSandboxOperationSandboxesSandboxIdCancelPostErrors];

export type CancelSandboxOperationSandboxesSandboxIdCancelPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type CancelSandboxOperationSandboxesSandboxIdCancelPostResponse = CancelSandboxOperationSandboxesSandboxIdCancelPostResponses[keyof CancelSandboxOperationSandboxesSandboxIdCancelPostResponses];

export type ExecCommandData = {
    body: ExecRequest;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query?: never;
    url: '/sandboxes/{sandbox_id}/exec';
};

export type ExecCommandErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecCommandError = ExecCommandErrors[keyof ExecCommandErrors];

export type ExecCommandResponses = {
    /**
     * Successful Response
     */
    200: ExecResponse;
};

export type ExecCommandResponse = ExecCommandResponses[keyof ExecCommandResponses];

export type ReadFileSandboxesSandboxIdFilesGetData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/sandboxes/{sandbox_id}/files';
};

export type ReadFileSandboxesSandboxIdFilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadFileSandboxesSandboxIdFilesGetError = ReadFileSandboxesSandboxIdFilesGetErrors[keyof ReadFileSandboxesSandboxIdFilesGetErrors];

export type ReadFileSandboxesSandboxIdFilesGetResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type ReadFileSandboxesSandboxIdFilesGetResponse = ReadFileSandboxesSandboxIdFilesGetResponses[keyof ReadFileSandboxesSandboxIdFilesGetResponses];

export type WriteFileSandboxesSandboxIdFilesPutData = {
    body?: never;
    path: {
        /**
         * Sandbox Id
         */
        sandbox_id: string;
    };
    query: {
        /**
         * Path
         */
        path: string;
    };
    url: '/sandboxes/{sandbox_id}/files';
};

export type WriteFileSandboxesSandboxIdFilesPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WriteFileSandboxesSandboxIdFilesPutError = WriteFileSandboxesSandboxIdFilesPutErrors[keyof WriteFileSandboxesSandboxIdFilesPutErrors];

export type WriteFileSandboxesSandboxIdFilesPutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type WriteFileSandboxesSandboxIdFilesPutResponse = WriteFileSandboxesSandboxIdFilesPutResponses[keyof WriteFileSandboxesSandboxIdFilesPutResponses];
